### ISSUE TITLE
Version issue when installing zip from release.sh

### ISSUE THREAD

**Issue by nm17** [mitxela/kicad-round-tracks#10]
![2022-05-03_02-29](https://user-images.githubusercontent.com/23419131/166337380-6daec66e-8bcf-4eb7-a7f5-bd451bfbbcab.png)

**Comment by mitxela** [comment]
This is intentional - `git describe --dirty` sticks the commit hash on the end if you haven't tagged the release.

I honestly didn't expect anyone except me to use release.sh. If you want to install manually, just clone or unzip the repo in a plugin folder. You can then pull updates easily too.
