### ISSUE TITLE
Feature request: only generate teardrops

### ISSUE THREAD

**Issue by elcojacobs** [mitxela/kicad-round-tracks#14]
Hi!

Watched your video on Youtube and just tried the plugin.
I don't like the look of round tracks for all my PCBs, but widening a thin trace around a via is always good.

Would it be possible to not round any corners, but only apply teardrops?
Perhaps it could also be a setting to only apply to vias or to vias and pads.

**Comment by rmackinnon** [comment]
FYI teardrops are generated with [this](https://github.com/NilujePerchut/kicad_scripts) plugin.

**Comment by mitxela** [comment]
Yep the teardrops are completely separate from the track rounding already.
