### ISSUE TITLE
plug in cannot start

### ISSUE THREAD

**Issue by CMMS-Freather** [mitxela/kicad-round-tracks#17]
first of all, thank you for providing any feedback
I tried this plugin with kicad 5.1.12, on windows 10. 
The issue is I cannot have the plug in started. It keeps giving me 
AttributeError: 'BOARD_DESIGN_SETTINGS' object has no attribute 'GetNetClasses'
![image](https://user-images.githubusercontent.com/72902384/175160315-88210423-96f1-4380-bbcd-5ff1de8a8618.png)

Since it is something related to the board setttings, I opened my board set up and I do see net classes there. Screen shot as below
![image](https://user-images.githubusercontent.com/72902384/175160353-36316de8-ec77-4b1d-b329-edc7122b4705.png)
am I missing anything?

**Comment by mitxela** [comment]
Please use the kicad-5 branch (you can select it in the dropdown menu on the main page) https://github.com/mitxela/kicad-round-tracks/tree/kicad-5
