### ISSUE TITLE
[Feature Request] Unrounding Tracks

### ISSUE THREAD

**Issue by vishnumaiea** [mitxela/kicad-round-tracks#20]
Just like we have the rounding option, it would be useful if we also have the **unrounding** option. This can be used when the rounding is performed using native fillets which are adjustable after application. I can remove the rounding simply by dragging a corner. Currently, applying a 0 rounding doesn't work. Unrounding can be applied to the select track or the entire board.

**Comment by mitxela** [comment]
An attempt has been made to implement unrounding. There are many problems relating to coordinate rounding errors, so an unrounded PCB probably won't match the source file exactly.
