### ISSUE TITLE
kicad 7 freezes on macos 12.6.3 (monterey)

### ISSUE THREAD

**Issue by ewanuno** [mitxela/kicad-round-tracks#24]
After discovering that the version from the plugin manager in kicad 7 is broken, i installed kicad-round-tracks from the git.

 the plugin loads and starts but progress stays at 0% and never exits, the cpu isn't doing anything.
 i have attached a screen capture of the kicad error log
 
![kicard-round tracks error log](https://user-images.githubusercontent.com/2670261/223998854-3a78a545-93f2-4221-968a-6b27d1fd6fbf.png)

**Comment by mitxela** [comment]
see #22, it's due to a glitch in kicad, it will be fixed in 7.0.1. Until then you can use kicad nightly.
