### ISSUE TITLE
Some T-connections don't get rounded !

### ISSUE THREAD

**Issue by FredM67** [mitxela/kicad-round-tracks#9]
Here's a piece of my PCB...
![2022-04-28 22_04_24-_3phaseDiverter — PCB Editor](https://user-images.githubusercontent.com/45318189/165836919-5753b0ff-ae7e-4b58-896b-7ae5d2c31337.png)

After calling the plugin, here's what I get:
![2022-04-28 22_06_24-_3phaseDiverter — PCB Editor](https://user-images.githubusercontent.com/45318189/165837045-5dbb7ffd-337a-4a0c-a668-b1400d45194d.png)

Both blue T-Connections on the left and in the middle-right don't get round. The other ones (middle-left and the 2 on the right) are rounded properly... Strange !

**Comment by mitxela** [comment]
Two reasons this can happen. First is that the long horizontal track is one piece, so where the vertical track touches it, it isn't considered a junction. You can fix it by splitting the long track, or just redrawing the vertical one. Usually, when you draw a T-junction KiCad will split the track properly, but not always, depending on how it was drawn.

The other way this can happen is if the ends of the track are close but not quite touching. To be considered a join, the track ends need to be within 10nm of each other. This can sometimes happen if you switch grid sizes. If you right click / properties on each track, you can see their start and end positions, maybe one of them is on the grid while the other has 0.001 offset or something.

**Comment by FredM67** [comment]
> Two reasons this can happen. First is that the long horizontal track is one piece, so where the vertical track touches it, it isn't considered a junction. You can fix it by splitting the long track, or just redrawing the vertical one. Usually, when you draw a T-junction KiCad will split the track properly, but not always, depending on how it was drawn.
Yes, it was btw intentional to have both variants just to analyse the problem. Now it's ok, I had to completely redraw these track.

> The other way this can happen is if the ends of the track are close but not quite touching. To be considered a join, the track ends need to be within 10nm of each other. This can sometimes happen if you switch grid sizes. If you right click / properties on each track, you can see their start and end positions, maybe one of them is on the grid while the other has 0.001 offset or something.
Yes, this point is quite tricky... a "magnet" feature should be added inside the function "Cleanup track" as it happens when drawing a track.

By the way, I encounter another problem with junctions like this one:
![2022-04-29 11_34_37-_3phaseDiverter-rounded — PCB Editor](https://user-images.githubusercontent.com/45318189/165920313-01036066-5dc7-424e-b9b5-4a31edf71d0e.png)

After rounding I get:
![2022-04-29 11_35_02-_3phaseDiverter-rounded — PCB Editor](https://user-images.githubusercontent.com/45318189/165920372-9958379b-95e0-4652-86eb-1a56cf677d03.png)
This leads the Teardrop plugin to do simply nothing there, because the arc is "passing through"

Same happen with another linear junction where a straight piece of track is created passing through the pad.

**Comment by mitxela** [comment]
Yeah that's a known issue ( https://github.com/mitxela/kicad-round-tracks/issues/4 ) will fix it when I get a chance
